global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'qlp-orchestrator'

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9090']
        labels:
          service: 'orchestrator'
          
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:9090']
        labels:
          service: 'temporal'
          
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'