name: CI Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'
  DOCKER_BUILDKIT: 1

jobs:
  # Linting job for all languages
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Go
            working-directory: ./services
          - name: Python
            working-directory: ./services
          - name: JavaScript
            working-directory: ./services
          - name: Terraform
            working-directory: ./infrastructure/terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        if: matrix.name == 'Go'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '**/go.sum'
      
      - name: Setup Python
        if: matrix.name == 'Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Setup Node.js
        if: matrix.name == 'JavaScript'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Lint Go code
        if: matrix.name == 'Go'
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          find . -name "*.go" -type f | xargs -I {} dirname {} | sort -u | while read dir; do
            echo "Linting $dir"
            cd $dir && golangci-lint run --timeout=5m || true
            cd -
          done
        working-directory: ${{ matrix.working-directory }}
      
      - name: Lint Python code
        if: matrix.name == 'Python'
        run: |
          pip install --upgrade pip
          pip install flake8 black mypy pylint
          find . -name "*.py" -type f -exec flake8 {} + || true
          find . -name "*.py" -type f -exec black --check {} + || true
          find . -name "*.py" -type f -exec pylint {} + || true
        working-directory: ${{ matrix.working-directory }}
      
      - name: Lint JavaScript code
        if: matrix.name == 'JavaScript'
        run: |
          # Install ESLint globally if package.json doesn't exist
          if [ ! -f package.json ]; then
            npm install -g eslint
          else
            npm ci
          fi
          find . -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" | xargs eslint || true
        working-directory: ${{ matrix.working-directory }}
      
      - name: Validate Terraform
        if: matrix.name == 'Terraform'
        run: |
          terraform init -backend=false
          terraform fmt -check -recursive
          terraform validate
        working-directory: ${{ matrix.working-directory }}

  # Test job for all services
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service:
          - orchestrator
          - quantum-core
          - ai-ml
          - blockchain
          - iot-edge
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '**/go.sum'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Check if service exists
        id: check_service
        run: |
          if [ -d "services/${{ matrix.service }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Go tests
        if: steps.check_service.outputs.exists == 'true'
        run: |
          if [ -f "services/${{ matrix.service }}/go.mod" ]; then
            cd services/${{ matrix.service }}
            go test -v -race -coverprofile=coverage.out ./...
            go tool cover -html=coverage.out -o coverage.html
          fi
      
      - name: Run Python tests
        if: steps.check_service.outputs.exists == 'true'
        run: |
          if [ -f "services/${{ matrix.service }}/requirements.txt" ]; then
            cd services/${{ matrix.service }}
            pip install -r requirements.txt
            pip install pytest pytest-cov
            pytest --cov=. --cov-report=html --cov-report=term || true
          fi
      
      - name: Run JavaScript tests
        if: steps.check_service.outputs.exists == 'true'
        run: |
          if [ -f "services/${{ matrix.service }}/package.json" ]; then
            cd services/${{ matrix.service }}
            npm ci
            npm test || true
          fi
      
      - name: Upload coverage reports
        if: steps.check_service.outputs.exists == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.service }}
          path: |
            services/${{ matrix.service }}/coverage.*
            services/${{ matrix.service }}/htmlcov/
            services/${{ matrix.service }}/coverage/

  # Build Docker images
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service:
          - orchestrator
          - quantum-core
          - ai-ml
          - blockchain
          - iot-edge
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Check if Dockerfile exists
        id: check_dockerfile
        run: |
          if [ -f "services/${{ matrix.service }}/Dockerfile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Build Docker image
        if: steps.check_dockerfile.outputs.exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          push: false
          tags: |
            qlp-uos/${{ matrix.service }}:latest
            qlp-uos/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref_name }}

  # Integration tests
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Compose
        run: |
          docker compose version
      
      - name: Run integration tests
        run: |
          # Start services with docker-compose
          docker compose -f docker-compose.yml up -d
          
          # Wait for services to be ready
          sleep 30
          
          # Run integration tests if they exist
          if [ -d "tests/integration" ]; then
            cd tests/integration
            # Add integration test commands here
            echo "Running integration tests..."
          fi
          
          # Cleanup
          docker compose down
      
      - name: Collect logs on failure
        if: failure()
        run: |
          docker compose logs > docker-compose-logs.txt
          
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-logs
          path: docker-compose-logs.txt

  # Terraform validation
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Terraform Init
        run: |
          cd infrastructure/terraform/azure
          terraform init -backend=false
      
      - name: Terraform Plan
        run: |
          cd infrastructure/terraform/azure
          # Create example tfvars for validation
          cp terraform.tfvars.example terraform.tfvars || echo "No example tfvars found"
          terraform plan -input=false || echo "Plan requires Azure credentials"

  # Summary job
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [lint, test, build, integration-test, terraform-plan]
    if: success()
    
    steps:
      - name: CI Pipeline Success
        run: |
          echo "✅ All CI checks passed successfully!"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"